### ISSUE TITLE
Ansible deployment fails

### ISSUE THREAD

**Issue by sb10** [theobarberbany/Kubernetes_on_Openstack#1]
Hi,

I'm following the guide (modified as needed to get things to work), but can't get past the ansible-playbook step:

```
$ ansible-playbook --flush-cache --become -i inventory/$CLUSTER/hosts cluster.yml
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/lustre/scratch117/sciops/team117/npg/sb10/k8scluster/kubespray/roles/vault/handlers/main.yml': line 44, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: unseal vault
  ^ here
```

(It also doesn't work with `ansible-playbook --flush-cache --become -i contrib/terraform/openstack/hosts cluster.yml`)

Any clues?

**Comment by theobarberbany** [comment]
Hi Sendu,

The default deployment shouldn’t try to interact with vault ( unless that’s changed! ;( )

I’m house hunting in York without a laptop right now so I can’t look myself, but I’ll try taking a look when I’m next at a computer.

Other than git grepping through the kubespray repo for anything potentially related that looks wrong, or checking the open issues (chances are someone’s got a PR in?)

In the mean while, or as a last resort, the GCP free trial takes about ten seconds to set up and will give you a running cluster in ~5 minutes...

Theo

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by wikiselev** [comment]
Hi Sendu,

You could also try our instructions: https://github.com/cellgeni/kubespray. They are based on Helen's and Theo's instructions but maybe more detailed.

Cheers,
Vlad

**Comment by theobarberbany** [comment]
( yep that should work for 2.5.0! )

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sb10** [comment]
Thanks @wikiselev , I got it to work based on your instructions.

**Comment by wikiselev** [comment]
Apparently your original error was due to `ansible-modules-hashivault` not installed, which is now required in version 2.6.0:
https://github.com/kubernetes-incubator/kubespray/issues/2764

This should fix the error: `pip install ansible-modules-hashivault` (but I am currently getting https error on the farm and can't install it myself, not sure what's going on...)
